services:
  php_apache:
    container_name: php_8.2_apache_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - /Users/nikolaygrishchenko/Downloads/localhost:/var/www/html
    networks:
      - company_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1.0
    container_name: mysql_8.1.0_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: books
      MYSQL_USER: user
    ports:
      - 3306:3306
    volumes:
      - /Users/nikolaygrishchenko/Downloads/localhost:/var/mysql
    networks:
      - company_network

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin_container
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - company_network

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_CREATE_TOPICS: "test:1:1"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /Users/nikolaygrishchenko/Downloads/localhost/docker.sock:/var/run/docker.sock
    networks:
      - company_network

  zookeeper:
    image: zookeeper
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    networks:
      - company_network

networks:
  company_network: